spring.application.name=SpringMCPDemo
spring.main.web-application-type=none
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=spring-mcp-demo
spring.ai.mcp.server.version=0.0.1

spring.main.banner-mode=off
logging.level.root=OFF